### ISSUE TITLE
Head Tracker for DCS 

### ISSUE THREAD

**Issue by junjiali** [brumster/EDTracker2_ArduinoHardware#6]
There's no way to contact you and edtracker.org.uk is down. I want to try out the content you've provided with the recommended hardware. The GUI doesn't seem to work as the website is down. I'm not familiar with Arduino IDE as such but I wish to utilize the code and the service that you were providing. 

Is there any way you can help me out? I'll be extremely thankful!

**Comment by brumster** [comment]
Hi! GUI still works; just flashing within it doesn't work any more. Essentially I need to re-write the website onto GitHub wiki pages or provide some sort of guide, which I'll put as a back-burner task... but I'm afraid I don't have any immediate time right now to do it. I'll mark this as community support and maybe someone else can help you.

**Comment by junjiali** [comment]
> Hi! GUI still works; just flashing within it doesn't work any more. Essentially I need to re-write the website onto GitHub wiki pages or provide some sort of guide, which I'll put as a back-burner task... but I'm afraid I don't have any immediate time right now to do it. I'll mark this as community support and maybe someone else can help you.

**Comment by junjiali** [comment]
Thank you so much for taking out the time to reply to my

**Comment by junjiali** [comment]
Thank you for taking out the time to reply to this.
Since I have the files you've uploaded here and after some reading and going through some of your videos, I kind of understood a way of making it work (if it works).

So, I need the following items:

1. Arduino Pro Micro 5V 16Mhz (ATMEGA32U4)
2. MPU-9250
3. Tactile switch
4. FR4 Double-sided Veroboard (+ breadboard to test things)
5. Micro-USB data cable.

Procedure:

Using the schematics that you've provided. (I suppose MPU 9250 and 9150 are connected the same way) I will be assembling the components and connecting them to a breadboard.
I'll be using a micro-USB data cable to plug it into my system.

Now, here comes the tricky part.
According to the files that you've provided there are two formats/file types.

a) .hex file - the firmware
b) .ino for the Arduino IDE(?)

Once, I've assembled everything what should I be doing at this stage? Am I supposed to flash the device using another tool since the GUI doesn't work or use the .ino file?

And if the file gets flashed or uploaded onto the controller. Will I be able to use the GUI for calibration and use it with Opentrack?


Thank you again, Dan. 

Kind regards.

**Comment by brumster** [comment]
Basically once you've assembled, there are/were a number of approaches for flashing the firmware into the device.
1) The GUI would download and flash the firmware in for you, but this no longer works because the website of the company that used to host it has disappeared, and I can't update the GUI software to do it differently because the author of the GUI has not open-sourced the source code.
2) There is a command-line Java-based tool to flash firmwares into the device; it's under tools
3) You can compile from source and flash in via the Arduino IDE - which is where you download the two packages you see hosted here on GitHub.

The UI is still used to calibrate and configure the device once you've flashed it, it's just the flashing process itself that no longer works within it.
